language: rust
rust:
  - 1.15.0
  - 1.16.0
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc

# Use Travis container-based infrastructure
sudo: false
